name: eloquent xavier

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    - 
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Build and push the core docker image
      run: |
        DOCKER_REPO_1=ghcr.io/autocore-ats/core-focal-xavier:latest
        docker buildx build --output "type=image,push=true" --platform linux/arm64 --tag ${DOCKER_REPO_1} --file core.bionic.xavier.dockerfile .
    - 
      name: Build and push the base docker image
      run: |
        DOCKER_REPO_2=ghcr.io/autocore-ats/base-eloquent-xavier:latest
        docker buildx build --output "type=image,push=true" --platform linux/arm64 --build-arg FROM_IMAGE=${DOCKER_REPO_1} --tag ${DOCKER_REPO_2} --file base.eloquent.xavier.dockerfile .
    - 
      name: Build and push the runtime docker image
      run: |
        DOCKER_REPO_3=ghcr.io/autocore-ats/runtime-eloquent-xavier:latest
        docker buildx build --output "type=image,push=true" --platform linux/arm64 --build-arg FROM_IMAGE=${DOCKER_REPO_2} --tag ${DOCKER_REPO_3} --file runtime.eloquent.xavier.dockerfile .
    - 
      name: Build and push the build docker image
      run: |
        DOCKER_REPO_4=ghcr.io/autocore-ats/build-eloquent-xavier:latest
        docker buildx build --output "type=image,push=true" --platform linux/arm64 --build-arg FROM_IMAGE=${DOCKER_REPO_3} --tag ${DOCKER_REPO_4} --file build.eloquent.xavier.dockerfile .
    - 
      name: Build and push the devel docker image
      run: |
        DOCKER_REPO_5=ghcr.io/autocore-ats/devel-eloquent-xavier:latest
        docker buildx build --output "type=image,push=true" --platform linux/arm64 --build-arg FROM_IMAGE=${DOCKER_REPO_4} --tag ${DOCKER_REPO_5} --file devel.eloquent.xavier.dockerfile .